<div class="block newsletter">
                <div class="pdnewsletter">
                    <div class="title"><strong><?= $block->escapeHtml(__('Stay up to date')) ?></strong></div>
                    <div class="title-description"><?= $block->escapeHtml(__('Sign up for our newsletter to get the lastest news, announcements and event information')) ?></div>
                    <div class="content">
                        <form class="form subscribe"
                            novalidate
                            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                            method="post"
                            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                            id="newsletter-validate-detail">
                            <div class="field newsletter">
                                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                                <div class="control">
                                    <input name="email" type="email" id="newsletter"
                                                placeholder="<?= $block->escapeHtmlAttr(__('Enter your email adress')) ?>"
                                                data-validate="{required:true, 'validate-email':true}"/>
                                </div>
                            </div>
                            <div class="actions">
                                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                                    <span><?= $block->escapeHtml(__('Sign up')) ?></span>
                                </button>
                            </div>
                        </form>
                    </div>
                    <?= $block->getChildHtml(); ?>
                </div>
            </div>